/* Catalog logins — generated by build/make_user.mjs. Password hashes are
   PBKDF2-SHA256 (safe to commit). Never commit AUTH_SECRET — set it in Vercel. */
export default {
  "users": [
    {
      "u": "kuznetsov",
      "name": "Кузнецов В.Е. (владелец)",
      "role": "permanent",
      "expires": null,
      "salt": "_fCG0ztEJCuQbHNFvvtr0Q",
      "hash": "mMbFnfShEInV3SoWAl0IMbTYvxx-p6cvbjpVQFe_In4",
      "iters": 120000
    },
    {
      "u": "user",
      "name": "Временный доступ",
      "role": "temporary",
      "expires": "2026-09-22",
      "salt": "B2YCJYVGgs824TphapPcFw",
      "hash": "WEUu_tUUlUYmmvrvgW8m0WJiuo75w8RbmXN3s5HLjuc",
      "iters": 120000
    }
  ]
};
